-- ==============================================================================
-- CUSTOMER CHURN PREDICTOR & ENTERPRISE PORTAL: COMBINED DATABASE SCRIPT
-- Target: PostgreSQL 15+ / Supabase
-- Description: Single-file execution containing:
--   1. Schema Creation (users, employees, tasks, & predictions_log tables)
--   2. Safe Migrations & Unique Constraints (Guaranteed 42P10-proof)
--   3. Performance Indexes (Unique index enforcement on email)
--   4. Row Level Security (RLS) & Policies
--   5. Documentation & Metadata Comments
--   6. Analytical Views for Churn Intelligence
--   7. Safe Seed Data (Initial demo analyst user, enterprise employees, & predictions)
-- ==============================================================================

-- ==============================================================================
-- 1. TABLES DEFINITION & SAFE MIGRATIONS
-- ==============================================================================

-- 1.1 Users Table (Authentication & User Profile)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    is_google_auth BOOLEAN DEFAULT FALSE,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Migration safety for public.users
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_google_auth BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Deduplicate any existing duplicate emails in public.users and enforce unique constraint
DO $$
BEGIN
    DELETE FROM public.users a USING public.users b
    WHERE a.id > b.id AND LOWER(a.email) = LOWER(b.email) AND a.email IS NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
        WHERE c.conrelid = 'public.users'::regclass
          AND c.contype = 'u'
          AND a.attname = 'email'
    ) THEN
        ALTER TABLE public.users ADD CONSTRAINT uq_users_email UNIQUE (email);
    END IF;
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN
        NULL;
END $$;

-- 1.2 Employees Table (Supports manual insertion & seeded records)
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role VARCHAR(150) NOT NULL,
    job_title VARCHAR(150),
    department VARCHAR(100) NOT NULL,
    avatar_initials VARCHAR(10) DEFAULT 'EM',
    email VARCHAR(255) UNIQUE,
    is_seeded BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Migration safety for public.employees
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS role VARCHAR(150);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS job_title VARCHAR(150);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS avatar_initials VARCHAR(10) DEFAULT 'EM';
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS is_seeded BOOLEAN DEFAULT FALSE;

-- Deduplicate any existing duplicate emails in public.employees and enforce unique constraint
DO $$
BEGIN
    DELETE FROM public.employees a USING public.employees b
    WHERE a.id > b.id AND LOWER(a.email) = LOWER(b.email) AND a.email IS NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
        WHERE c.conrelid = 'public.employees'::regclass
          AND c.contype = 'u'
          AND a.attname = 'email'
    ) THEN
        ALTER TABLE public.employees ADD CONSTRAINT uq_employees_email UNIQUE (email);
    END IF;
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN
        NULL;
END $$;

-- 1.3 Tasks Table (Churn Predictions with Nullable employee_id)
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    customer_name VARCHAR(255) NOT NULL,
    contract VARCHAR(50),
    tenure INTEGER,
    monthly_charges NUMERIC(10, 2),
    churn_probability DOUBLE PRECISION NOT NULL,
    risk_level VARCHAR(50),
    input_features JSONB NOT NULL,
    top_factors JSONB NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 1.4 Predictions Log Table (Inference History & Employee Tasks)
CREATE TABLE IF NOT EXISTS public.predictions_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    input_features JSONB NOT NULL,
    churn_probability DOUBLE PRECISION NOT NULL,
    top_factors JSONB NOT NULL
);

-- Ensure column exists on existing tables
ALTER TABLE public.predictions_log 
    ADD COLUMN IF NOT EXISTS employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL;

-- ==============================================================================
-- 2. PERFORMANCE INDEXES (UNIQUE CONSTRAINTS ENFORCED)
-- ==============================================================================

-- Index on email for rapid authentication queries (enforcing uniqueness)
DROP INDEX IF EXISTS public.idx_users_email;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email 
    ON public.users (email);

-- Index on employee department, email & seeded status (enforcing uniqueness)
CREATE INDEX IF NOT EXISTS idx_employees_department 
    ON public.employees (department);
DROP INDEX IF EXISTS public.idx_employees_email;
CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_email 
    ON public.employees (email);
CREATE INDEX IF NOT EXISTS idx_employees_seeded 
    ON public.employees (is_seeded);

-- Index on prediction timestamp for time-series aggregation
CREATE INDEX IF NOT EXISTS idx_predictions_log_timestamp 
    ON public.predictions_log (timestamp DESC);

-- Index on churn probability for filtering high-risk subscribers
CREATE INDEX IF NOT EXISTS idx_predictions_log_churn_prob 
    ON public.predictions_log (churn_probability);

-- Index on user_id for relational lookups
CREATE INDEX IF NOT EXISTS idx_predictions_log_user_id 
    ON public.predictions_log (user_id);

-- Index on employee_id for task assignment lookups
CREATE INDEX IF NOT EXISTS idx_predictions_log_employee_id 
    ON public.predictions_log (employee_id);

-- Indexes on tasks table
CREATE INDEX IF NOT EXISTS idx_tasks_employee_id 
    ON public.tasks (employee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_churn_prob 
    ON public.tasks (churn_probability);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at 
    ON public.tasks (created_at DESC);

-- ==============================================================================
-- 3. ROW LEVEL SECURITY (RLS) & POLICIES
-- ==============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions_log ENABLE ROW LEVEL SECURITY;

-- Clean existing policies if re-running
DROP POLICY IF EXISTS "Allow public select on users" ON public.users;
DROP POLICY IF EXISTS "Allow public insert on users" ON public.users;
DROP POLICY IF EXISTS "Allow public select on employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public insert on employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public update on employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public select on tasks" ON public.tasks;
DROP POLICY IF EXISTS "Allow public insert on tasks" ON public.tasks;
DROP POLICY IF EXISTS "Allow public update on tasks" ON public.tasks;
DROP POLICY IF EXISTS "Allow public select on predictions_log" ON public.predictions_log;
DROP POLICY IF EXISTS "Allow public insert on predictions_log" ON public.predictions_log;

-- Users table policies
CREATE POLICY "Allow public select on users" 
    ON public.users 
    FOR SELECT 
    USING (true);

CREATE POLICY "Allow public insert on users" 
    ON public.users 
    FOR INSERT 
    WITH CHECK (true);

-- Employees table policies
CREATE POLICY "Allow public select on employees" 
    ON public.employees 
    FOR SELECT 
    USING (true);

CREATE POLICY "Allow public insert on employees" 
    ON public.employees 
    FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Allow public update on employees" 
    ON public.employees 
    FOR UPDATE 
    USING (true);

-- Tasks table policies
CREATE POLICY "Allow public select on tasks" 
    ON public.tasks 
    FOR SELECT 
    USING (true);

CREATE POLICY "Allow public insert on tasks" 
    ON public.tasks 
    FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Allow public update on tasks" 
    ON public.tasks 
    FOR UPDATE 
    USING (true);

-- Predictions log policies
CREATE POLICY "Allow public select on predictions_log" 
    ON public.predictions_log 
    FOR SELECT 
    USING (true);

CREATE POLICY "Allow public insert on predictions_log" 
    ON public.predictions_log 
    FOR INSERT 
    WITH CHECK (true);

-- ==============================================================================
-- 4. DOCUMENTATION & METADATA COMMENTS
-- ==============================================================================

COMMENT ON TABLE public.users IS 'Registered application users with bcrypt-hashed credentials and Google OAuth support';
COMMENT ON COLUMN public.users.hashed_password IS 'Bcrypt password hash ($2b$12$...)';
COMMENT ON COLUMN public.users.is_google_auth IS 'Boolean flag indicating whether the user authenticated via Google OAuth 2.0';
COMMENT ON TABLE public.employees IS 'Enterprise retention team members assigned to customer churn tasks';
COMMENT ON TABLE public.tasks IS 'Assigned customer churn remediation tasks for retention specialists';
COMMENT ON TABLE public.predictions_log IS 'Logs of customer churn predictions and local SHAP feature attributions';
COMMENT ON COLUMN public.predictions_log.employee_id IS 'Assigned employee foreign key for task queue linking';
COMMENT ON COLUMN public.predictions_log.input_features IS 'Customer input attributes snapshot in JSONB format';
COMMENT ON COLUMN public.predictions_log.churn_probability IS 'Predicted churn probability between 0.0000 and 1.0000';
COMMENT ON COLUMN public.predictions_log.top_factors IS 'Top 5 local SHAP attributions indicating directional feature impacts';

-- ==============================================================================
-- 5. ANALYTICAL VIEWS
-- ==============================================================================

-- 5.1 View: High-Risk At-Risk Customer Queue (Probability >= 65%)
CREATE OR REPLACE VIEW public.vw_high_risk_customers AS
SELECT 
    p.id AS prediction_id,
    p.timestamp,
    p.churn_probability,
    p.input_features->>'Contract' AS contract_type,
    p.input_features->>'tenure' AS tenure_months,
    p.input_features->>'MonthlyCharges' AS monthly_charges,
    p.input_features->>'InternetService' AS internet_service,
    p.top_factors->0->>'feature' AS primary_churn_driver,
    e.name AS assigned_employee_name,
    e.role AS assigned_employee_role,
    u.name AS evaluated_by_user
FROM public.predictions_log p
LEFT JOIN public.employees e ON p.employee_id = e.id
LEFT JOIN public.users u ON p.user_id = u.id
WHERE p.churn_probability >= 0.65;

-- 5.2 View: Churn Risk Summary by Contract Type
CREATE OR REPLACE VIEW public.vw_contract_churn_summary AS
SELECT 
    input_features->>'Contract' AS contract_type,
    COUNT(*) AS total_evaluations,
    ROUND(AVG(churn_probability)::numeric, 4) AS avg_churn_rate,
    COUNT(*) FILTER (WHERE churn_probability >= 0.65) AS high_risk_count,
    COUNT(*) FILTER (WHERE churn_probability < 0.35) AS low_risk_count
FROM public.predictions_log
GROUP BY contract_type;

-- ==============================================================================
-- 6. INITIAL SEED DATA (SAFE, IDEMPOTENT, ZERO 42P10 CONFLICT RISK)
-- ==============================================================================

-- 6.1 Demo Analyst User
-- Password is: SecurePassword2026! (bcrypt hash: $2b$12$CyuMTaR8Euni3L0r9slld.GYx59B9yvB8h55P4x1Y7m9hDq0KqC82)
INSERT INTO public.users (name, email, hashed_password)
SELECT 
    'Demo ML Analyst',
    'demo.analyst@company.com',
    '$2b$12$CyuMTaR8Euni3L0r9slld.GYx59B9yvB8h55P4x1Y7m9hDq0KqC82'
WHERE NOT EXISTS (
    SELECT 1 FROM public.users WHERE LOWER(email) = LOWER('demo.analyst@company.com')
);

-- 6.2 Enterprise Employees
INSERT INTO public.employees (name, full_name, role, job_title, department, avatar_initials, email, is_seeded)
SELECT v.name, v.full_name, v.role, v.job_title, v.department, v.avatar_initials, v.email, TRUE
FROM (VALUES 
    ('Elena Rostova', 'Elena Rostova', 'Senior Retention Specialist', 'Senior Retention Specialist', 'Customer Success', 'ER', 'elena.rostova@enterprise.ai'),
    ('Marcus Vance', 'Marcus Vance', 'Key Account Executive', 'Key Account Executive', 'Enterprise Accounts', 'MV', 'marcus.vance@enterprise.ai'),
    ('Sarah Chen', 'Sarah Chen', 'Churn Risk Analyst', 'Churn Risk Analyst', 'Risk & Operations', 'SC', 'sarah.chen@enterprise.ai'),
    ('David Miller', 'David Miller', 'Customer Lifecycle Manager', 'Customer Lifecycle Manager', 'Client Operations', 'DM', 'david.miller@enterprise.ai')
) AS v(name, full_name, role, job_title, department, avatar_initials, email)
WHERE NOT EXISTS (
    SELECT 1 FROM public.employees e WHERE LOWER(e.email) = LOWER(v.email)
);

-- 6.3 Sample Predictions Linked to Employees dynamically
INSERT INTO public.predictions_log (employee_id, input_features, churn_probability, top_factors)
SELECT 
    (SELECT id FROM public.employees WHERE email = 'elena.rostova@enterprise.ai' LIMIT 1),
    '{
        "customer_name": "Acme Global Dynamics",
        "gender": "Female",
        "SeniorCitizen": 0,
        "Partner": "No",
        "Dependents": "No",
        "tenure": 2,
        "Contract": "Month-to-month",
        "PaperlessBilling": "Yes",
        "PaymentMethod": "Electronic check",
        "MonthlyCharges": 94.5,
        "TotalCharges": 189.0,
        "InternetService": "Fiber optic",
        "OnlineSecurity": "No",
        "TechSupport": "No"
    }'::jsonb,
    0.9175,
    '[
        {"feature": "Contract_Month-to-month", "shap_value": 0.6359, "effect": "Increases Churn Risk"},
        {"feature": "tenure", "shap_value": 0.5556, "effect": "Increases Churn Risk"},
        {"feature": "MonthlyCharges", "shap_value": 0.4307, "effect": "Increases Churn Risk"},
        {"feature": "PaymentMethod_Electronic check", "shap_value": 0.3849, "effect": "Increases Churn Risk"},
        {"feature": "InternetService_Fiber optic", "shap_value": 0.2695, "effect": "Increases Churn Risk"}
    ]'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM public.predictions_log 
    WHERE input_features->>'customer_name' = 'Acme Global Dynamics'
);

INSERT INTO public.predictions_log (employee_id, input_features, churn_probability, top_factors)
SELECT 
    (SELECT id FROM public.employees WHERE email = 'marcus.vance@enterprise.ai' LIMIT 1),
    '{
        "customer_name": "Starlight Logistics",
        "gender": "Male",
        "SeniorCitizen": 0,
        "Partner": "Yes",
        "Dependents": "Yes",
        "tenure": 62,
        "Contract": "Two year",
        "PaperlessBilling": "No",
        "PaymentMethod": "Bank transfer (automatic)",
        "MonthlyCharges": 42.0,
        "TotalCharges": 2604.0,
        "InternetService": "DSL",
        "OnlineSecurity": "Yes",
        "TechSupport": "Yes"
    }'::jsonb,
    0.0008,
    '[
        {"feature": "tenure", "shap_value": -2.8241, "effect": "Decreases Churn Risk"},
        {"feature": "Contract_Month-to-month", "shap_value": -1.1961, "effect": "Decreases Churn Risk"},
        {"feature": "TotalCharges", "shap_value": -0.7669, "effect": "Decreases Churn Risk"},
        {"feature": "InternetService_Fiber optic", "shap_value": -0.5583, "effect": "Decreases Churn Risk"},
        {"feature": "Contract_Two year", "shap_value": -0.4663, "effect": "Decreases Churn Risk"}
    ]'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM public.predictions_log 
    WHERE input_features->>'customer_name' = 'Starlight Logistics'
);

INSERT INTO public.predictions_log (employee_id, input_features, churn_probability, top_factors)
SELECT 
    (SELECT id FROM public.employees WHERE email = 'elena.rostova@enterprise.ai' LIMIT 1),
    '{
        "customer_name": "Nexus Retail Corp",
        "gender": "Female",
        "SeniorCitizen": 1,
        "Partner": "Yes",
        "Dependents": "No",
        "tenure": 18,
        "Contract": "One year",
        "PaperlessBilling": "Yes",
        "PaymentMethod": "Credit card (automatic)",
        "MonthlyCharges": 78.0,
        "TotalCharges": 1404.0,
        "InternetService": "Fiber optic",
        "OnlineSecurity": "Yes",
        "TechSupport": "No"
    }'::jsonb,
    0.3642,
    '[
        {"feature": "Contract_One year", "shap_value": -0.4215, "effect": "Decreases Churn Risk"},
        {"feature": "MonthlyCharges", "shap_value": 0.2854, "effect": "Increases Churn Risk"},
        {"feature": "tenure", "shap_value": -0.1982, "effect": "Decreases Churn Risk"}
    ]'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM public.predictions_log 
    WHERE input_features->>'customer_name' = 'Nexus Retail Corp'
);

-- Output confirmation notice
SELECT 'Database schema, employees table, security policies, analytical views, and seed data applied successfully!' AS status;
