-- ==============================================================================
-- Customer Churn Predictor: Enterprise Database Schema (Phase 1 Expansion)
-- Compatible with: Supabase (PostgreSQL 15+)
-- Features:
--   1. Users Table (Bcrypt authentication & Google OAuth profile)
--   2. Employees Table (Supports both Faker 50-seed & Manual staff insertions)
--   3. Tasks Table (Churn prediction tasks with nullable employee_id foreign key)
--   4. Predictions Log Table (Legacy inference logs)
--   5. Row Level Security (RLS) & Performance Unique Indexes
-- ==============================================================================

-- 1. Users Table (Authentication & User Management)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    is_google_auth BOOLEAN DEFAULT FALSE,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Migration safety: Ensure columns exist on older tables
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_google_auth BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Deduplicate any existing duplicate emails in public.users and enforce unique constraint
DO $$
BEGIN
    DELETE FROM public.users a USING public.users b
    WHERE a.id > b.id AND LOWER(a.email) = LOWER(b.email) AND a.email IS NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
        WHERE c.conrelid = 'public.users'::regclass
          AND c.contype = 'u'
          AND a.attname = 'email'
    ) THEN
        ALTER TABLE public.users ADD CONSTRAINT uq_users_email UNIQUE (email);
    END IF;
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN
        NULL;
END $$;

DROP INDEX IF EXISTS public.idx_users_email;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON public.users (email);


-- 2. Employees Table (Supports manual customer insertion & seeded records)
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role VARCHAR(150) NOT NULL,
    job_title VARCHAR(150),
    department VARCHAR(100) NOT NULL,
    avatar_initials VARCHAR(10) DEFAULT 'EM',
    email VARCHAR(255) UNIQUE,
    is_seeded BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Migration safety: Add columns if table exists in older state
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS role VARCHAR(150);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS job_title VARCHAR(150);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS avatar_initials VARCHAR(10) DEFAULT 'EM';
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS is_seeded BOOLEAN DEFAULT FALSE;

-- Deduplicate any existing duplicate emails in public.employees and enforce unique constraint
DO $$
BEGIN
    DELETE FROM public.employees a USING public.employees b
    WHERE a.id > b.id AND LOWER(a.email) = LOWER(b.email) AND a.email IS NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
        WHERE c.conrelid = 'public.employees'::regclass
          AND c.contype = 'u'
          AND a.attname = 'email'
    ) THEN
        ALTER TABLE public.employees ADD CONSTRAINT uq_employees_email UNIQUE (email);
    END IF;
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN
        NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_employees_department ON public.employees (department);
DROP INDEX IF EXISTS public.idx_employees_email;
CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_email ON public.employees (email);
CREATE INDEX IF NOT EXISTS idx_employees_seeded ON public.employees (is_seeded);


-- 3. Tasks Table (Churn Predictions with Nullable employee_id)
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    customer_name VARCHAR(255) NOT NULL,
    contract VARCHAR(50),
    tenure INTEGER,
    monthly_charges NUMERIC(10, 2),
    churn_probability DOUBLE PRECISION NOT NULL,
    risk_level VARCHAR(50),
    input_features JSONB NOT NULL,
    top_factors JSONB NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_employee_id ON public.tasks (employee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_churn_prob ON public.tasks (churn_probability);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON public.tasks (created_at DESC);


-- 4. Predictions Log (Historical / Legacy Inferences)
CREATE TABLE IF NOT EXISTS public.predictions_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    input_features JSONB NOT NULL,
    churn_probability DOUBLE PRECISION NOT NULL,
    top_factors JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_predictions_log_timestamp ON public.predictions_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_predictions_log_employee_id ON public.predictions_log (employee_id);


-- 5. Row Level Security (RLS) Configuration
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions_log ENABLE ROW LEVEL SECURITY;

-- Clean existing policies if re-running
DROP POLICY IF EXISTS "Allow public select on users" ON public.users;
DROP POLICY IF EXISTS "Allow public insert on users" ON public.users;
DROP POLICY IF EXISTS "Allow public select on employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public insert on employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public update on employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public select on tasks" ON public.tasks;
DROP POLICY IF EXISTS "Allow public insert on tasks" ON public.tasks;
DROP POLICY IF EXISTS "Allow public update on tasks" ON public.tasks;
DROP POLICY IF EXISTS "Allow public select on predictions_log" ON public.predictions_log;
DROP POLICY IF EXISTS "Allow public insert on predictions_log" ON public.predictions_log;

-- Allow select/insert/update policies for application clients
CREATE POLICY "Allow public select on users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert on users" ON public.users FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select on employees" ON public.employees FOR SELECT USING (true);
CREATE POLICY "Allow public insert on employees" ON public.employees FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on employees" ON public.employees FOR UPDATE USING (true);

CREATE POLICY "Allow public select on tasks" ON public.tasks FOR SELECT USING (true);
CREATE POLICY "Allow public insert on tasks" ON public.tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on tasks" ON public.tasks FOR UPDATE USING (true);

CREATE POLICY "Allow public select on predictions_log" ON public.predictions_log FOR SELECT USING (true);
CREATE POLICY "Allow public insert on predictions_log" ON public.predictions_log FOR INSERT WITH CHECK (true);
